# Generated by Django 6.0.3 on 2026-07-20 15:39

import django.db.models.deletion
import users.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instansi",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nama", models.CharField(max_length=150, unique=True)),
                (
                    "kode",
                    models.CharField(
                        help_text="Kode singkat instansi, mis. DPUPR.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("deskripsi", models.TextField(blank=True)),
                ("email_kontak", models.EmailField(blank=True, max_length=254)),
                ("telepon", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Instansi",
                "verbose_name_plural": "Instansi",
                "db_table": "instansi",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("nama_lengkap", models.CharField(max_length=150)),
                ("nomor_telepon", models.CharField(blank=True, max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("PETUGAS", "Petugas Instansi"),
                            ("WARGA", "Warga"),
                        ],
                        db_index=True,
                        default="WARGA",
                        max_length=10,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="avatar/%Y/%m/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "instansi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petugas",
                        to="users.instansi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengguna",
                "verbose_name_plural": "Pengguna",
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["role", "instansi"], name="users_role_baeb69_idx"
                    )
                ],
            },
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
