# Generated by Django 6.0.3 on 2026-07-20 15:39

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dukungan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dukungan",
                "verbose_name_plural": "Dukungan",
                "db_table": "dukungan",
            },
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nama", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "ikon",
                    models.CharField(
                        default="fa-triangle-exclamation",
                        help_text="Nama kelas ikon Font Awesome untuk penanda peta.",
                        max_length=50,
                    ),
                ),
                (
                    "warna",
                    models.CharField(
                        default="#dc2626",
                        help_text="Warna hex penanda peta.",
                        max_length=7,
                    ),
                ),
                (
                    "sla_hari",
                    models.PositiveSmallIntegerField(
                        default=7, help_text="Target penyelesaian dalam hari kerja."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
                "db_table": "kategori",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Laporan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nomor_tiket",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("judul", models.CharField(max_length=200)),
                ("deskripsi", models.TextField()),
                (
                    "lokasi",
                    django.contrib.gis.db.models.fields.PointField(
                        db_index=True, geography=True, srid=4326
                    ),
                ),
                ("alamat", models.CharField(blank=True, max_length=255)),
                (
                    "kelurahan",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "kecamatan",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="laporan/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BARU", "Baru"),
                            ("DIVERIFIKASI", "Diverifikasi"),
                            ("DIPROSES", "Sedang Diproses"),
                            ("SELESAI", "Selesai"),
                            ("DITOLAK", "Ditolak"),
                        ],
                        db_index=True,
                        default="BARU",
                        max_length=15,
                    ),
                ),
                (
                    "prioritas",
                    models.CharField(
                        choices=[
                            ("RENDAH", "Rendah"),
                            ("SEDANG", "Sedang"),
                            ("TINGGI", "Tinggi"),
                        ],
                        default="SEDANG",
                        max_length=10,
                    ),
                ),
                ("nama_pelapor", models.CharField(blank=True, max_length=150)),
                ("is_anonim", models.BooleanField(default=False)),
                ("diverifikasi_at", models.DateTimeField(blank=True, null=True)),
                ("diproses_at", models.DateTimeField(blank=True, null=True)),
                ("selesai_at", models.DateTimeField(blank=True, null=True)),
                ("catatan_penyelesaian", models.TextField(blank=True)),
                (
                    "foto_penyelesaian",
                    models.ImageField(
                        blank=True, null=True, upload_to="penyelesaian/%Y/%m/"
                    ),
                ),
                ("jumlah_dukungan", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Laporan",
                "verbose_name_plural": "Laporan",
                "db_table": "laporan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiwayatStatus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("status_lama", models.CharField(blank=True, max_length=15)),
                ("status_baru", models.CharField(max_length=15)),
                ("catatan", models.TextField(blank=True)),
                ("nama_oleh", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Riwayat Status",
                "verbose_name_plural": "Riwayat Status",
                "db_table": "riwayat_status",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tanggapan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nama_penulis", models.CharField(blank=True, max_length=150)),
                ("peran_penulis", models.CharField(blank=True, max_length=10)),
                ("isi", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Tanggapan",
                "verbose_name_plural": "Tanggapan",
                "db_table": "tanggapan",
                "ordering": ["created_at"],
            },
        ),
    ]
