# Generated by Django 6.0.3 on 2026-07-20 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dukungan",
            name="warga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dukungan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kategori",
            name="instansi_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kategori",
                to="users.instansi",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="instansi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laporan",
                to="users.instansi",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laporan",
                to="reports.kategori",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="pelapor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laporan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="petugas",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "PETUGAS"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laporan_ditangani",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dukungan",
            name="laporan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dukungan",
                to="reports.laporan",
            ),
        ),
        migrations.AddField(
            model_name="riwayatstatus",
            name="laporan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="riwayat",
                to="reports.laporan",
            ),
        ),
        migrations.AddField(
            model_name="riwayatstatus",
            name="oleh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tanggapan",
            name="laporan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tanggapan",
                to="reports.laporan",
            ),
        ),
        migrations.AddField(
            model_name="tanggapan",
            name="penulis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tanggapan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="laporan",
            index=models.Index(
                fields=["status", "kategori", "-created_at"],
                name="laporan_status_d733d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="laporan",
            index=models.Index(
                fields=["instansi", "status"], name="laporan_instans_d91d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laporan",
            index=models.Index(
                fields=["pelapor", "-created_at"], name="laporan_pelapor_b2a984_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dukungan",
            constraint=models.UniqueConstraint(
                fields=("laporan", "warga"), name="uniq_dukungan_per_warga"
            ),
        ),
    ]
