# Generated by Django 6.0.3 on 2026-07-20 15:39

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fasilitas",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nama", models.CharField(max_length=150)),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("KANTOR_DINAS", "Kantor Dinas"),
                            ("POSKO", "Posko Lapangan"),
                            ("PUSKESMAS", "Puskesmas"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("alamat", models.CharField(blank=True, max_length=255)),
                (
                    "lokasi",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Fasilitas",
                "verbose_name_plural": "Fasilitas",
                "db_table": "fasilitas",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Wilayah",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nama", models.CharField(db_index=True, max_length=120)),
                (
                    "kode",
                    models.CharField(
                        help_text="Kode wilayah BPS.", max_length=20, unique=True
                    ),
                ),
                (
                    "tingkat",
                    models.CharField(
                        choices=[
                            ("KOTA", "Kota/Kabupaten"),
                            ("KECAMATAN", "Kecamatan"),
                            ("KELURAHAN", "Kelurahan/Desa"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("jumlah_penduduk", models.PositiveIntegerField(blank=True, null=True)),
                ("luas_km2", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Wilayah",
                "verbose_name_plural": "Wilayah",
                "db_table": "wilayah",
                "ordering": ["tingkat", "nama"],
            },
        ),
    ]
