# Generated by Django 6.0.3 on 2026-07-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spatial", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasilitas",
            name="instansi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fasilitas",
                to="users.instansi",
            ),
        ),
        migrations.AddField(
            model_name="wilayah",
            name="induk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anak",
                to="spatial.wilayah",
            ),
        ),
        migrations.AddIndex(
            model_name="wilayah",
            index=models.Index(
                fields=["tingkat", "nama"], name="wilayah_tingkat_64dd14_idx"
            ),
        ),
    ]
